title: Subjects
modelClass: DS\Feedback\Models\FeedbackSubject
list: $/ds/feedback/models/feedbacksubject/columns.yaml
recordUrl: 'ds/feedback/subjects/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
